### ISSUE TITLE
 `<module:NumberHelper>': uninitialized constant ActiveSupport::Autoload (NameError)

### ISSUE THREAD

**Issue by rngadam** [heroku/databasedotcom#183]
After a bundle update, databasedotcom is encountering this issue when being required:

```
11:11:46 web.1  | /Library/Ruby/Gems/2.0.0/gems/activesupport-4.2.4/lib/active_support/number_helper.rb:3:in `<module:NumberHelper>': uninitialized constant ActiveSupport::Autoload (NameError)
11:11:46 web.1  | 	from /Library/Ruby/Gems/2.0.0/gems/activesupport-4.2.4/lib/active_support/number_helper.rb:2:in `<module:ActiveSupport>'
11:11:46 web.1  | 	from /Library/Ruby/Gems/2.0.0/gems/activesupport-4.2.4/lib/active_support/number_helper.rb:1:in `<top (required)>'
11:11:46 web.1  | 	from /Library/Ruby/Gems/2.0.0/gems/backports-3.6.6/lib/backports/std_lib.rb:9:in `require'
11:11:46 web.1  | 	from /Library/Ruby/Gems/2.0.0/gems/backports-3.6.6/lib/backports/std_lib.rb:9:in `require_with_backports'
11:11:46 web.1  | 	from /Library/Ruby/Gems/2.0.0/gems/activesupport-4.2.4/lib/active_support/core_ext/numeric/conversions.rb:2:in `<top (required)>'
11:11:46 web.1  | 	from /Library/Ruby/Gems/2.0.0/gems/backports-3.6.6/lib/backports/std_lib.rb:9:in `require'
11:11:46 web.1  | 	from /Library/Ruby/Gems/2.0.0/gems/backports-3.6.6/lib/backports/std_lib.rb:9:in `require_with_backports'
11:11:46 web.1  | 	from /Library/Ruby/Gems/2.0.0/gems/activesupport-4.2.4/lib/active_support/core_ext/numeric.rb:3:in `<top (required)>'
11:11:46 web.1  | 	from /Library/Ruby/Gems/2.0.0/gems/backports-3.6.6/lib/backports/std_lib.rb:9:in `require'
11:11:46 web.1  | 	from /Library/Ruby/Gems/2.0.0/gems/backports-3.6.6/lib/backports/std_lib.rb:9:in `require_with_backports'
11:11:46 web.1  | 	from /Library/Ruby/Gems/2.0.0/gems/activesupport-4.2.4/lib/active_support/core_ext.rb:2:in `block in <top (required)>'
11:11:46 web.1  | 	from /Library/Ruby/Gems/2.0.0/gems/activesupport-4.2.4/lib/active_support/core_ext.rb:1:in `each'
11:11:46 web.1  | 	from /Library/Ruby/Gems/2.0.0/gems/activesupport-4.2.4/lib/active_support/core_ext.rb:1:in `<top (required)>'
11:11:46 web.1  | 	from /Library/Ruby/Gems/2.0.0/gems/backports-3.6.6/lib/backports/std_lib.rb:9:in `require'
11:11:46 web.1  | 	from /Library/Ruby/Gems/2.0.0/gems/backports-3.6.6/lib/backports/std_lib.rb:9:in `require_with_backports'
11:11:46 web.1  | 	from /Library/Ruby/Gems/2.0.0/gems/databasedotcom-1.3.2/lib/databasedotcom.rb:1:in `<top (required)>'
11:11:46 web.1  | 	from /Library/Ruby/Gems/2.0.0/gems/backports-3.6.6/lib/backports/std_lib.rb:9:in `require'
11:11:46 web.1  | 	from /Library/Ruby/Gems/2.0.0/gems/backports-3.6.6/lib/backports/std_lib.rb:9:in `require_with_backports'
11:11:46 web.1  | 	from myapp.rb:10:in `<main>'
```

**Comment by freeformz** [comment]
This is happening during `require 'active_support'` and I don't think has anything to do with the databasedotcom gem itself. Maybe backports is messing something up?
